<?php

namespace frontend\controllers;


use Yii;
use yii\web\Controller;
use yii\web\Response;


class   CommonController extends Controller
{
    public $layout='index';
    public $uId;
    public $userInfo=[];
    public function init()
    {
        //用户信息
        $userInfo =json_decode(Yii::$app->session->get(Yii::$app->params['redisUserinfoKey']),true);
        Yii::$app->view->params['uId'] =$userInfo['uId'];
        $this->userInfo =$userInfo;
        empty($this->userInfo) ?   Yii::$app->view->params['loginStatus'] = 0 :  Yii::$app->view->params['loginStatus'] =1;
        Yii::$app->view->params['userInfo']=$userInfo;

        //seo
        $seo['title'] ='ITbook-收集最全最新最好的jQuery插件';
        $seo['keywords'] ='jQuery,jQuery特效,jQuery ui,jQuery插件,jQuery 教程,css3,网页特效,JS特效';
        $seo['description'] ='本站致力于收集jQuery插件和提供各种jQuery特效的详细使用方法,在线预览，jQuery插件下载及教程';
        Yii::$app->view->params['seo']=$seo;
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     *  404页面
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }


}
