<?php

namespace frontend\controllers;


use Yii;
use yii\web\Controller;
use yii\web\Response;


class   CommonController extends Controller
{
    public $layout='index';
    public $uId;
    public $userInfo=[];
    public function init()
    {
        $userInfo =json_decode(Yii::$app->session->get(Yii::$app->params['redisUserinfoKey']),true);
        $this->uId =$userInfo['uId'];
        $this->userInfo =$userInfo;
        Yii::$app->view->params['userInfo']=$userInfo;
        $seo['title'] ='ITbook-收集最全最新最好的jQuery插件';
        $seo['keywords'] ='jQuery,jQuery特效,jQuery ui,jQuery插件,jQuery 教程,css3,网页特效,JS特效';
        $seo['description'] ='本站致力于收集jQuery插件和提供各种jQuery特效的详细使用方法,在线预览，jQuery插件下载及教程';
        Yii::$app->view->params['seo']=$seo;
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     *  404页面
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }


    function actionUpload(){





//        $extensions = array("jpg","bmp","gif","png");
//        $uploadFilename = $_FILES['upload']['name'];
//        $uploadFilesize = $_FILES['upload']['size'];
//        if($uploadFilesize  > 1024*10*1000){
//            echo "<font color=\"red\"size=\"2\">*图片大小不能超过2M</font>";
//            exit;
//        }
//
//        $extension = pathInfo($uploadFilename,PATHINFO_EXTENSION);
//        if(in_array($extension,$extensions)){
//            $uploadPath ="./uploadfile/";
//            $uuid = str_replace('.','',uniqid("",TRUE)).".".$extension;
//            $desname = $uploadPath.$uuid;
//            $previewname = './uploadfile/'.$uuid;
//            $tag = move_uploaded_file($_FILES['upload']['tmp_name'],$desname);
//            $callback = $_REQUEST["CKEditorFuncNum"];
//            echo "<script type='text/javascript'>window.parent.CKEDITOR.tools.callFunction($callback,'".$previewname."','');</script>";
//        }else{
//            echo "<font color=\"red\"size=\"2\">*文件格式不正确（必须为.jpg/.gif/.bmp/.png文件）</font>";
//        }
    }


}
