<?php

namespace frontend\controllers;


use frontend\models\WebSource;
use Yii;
use yii\web\Controller;
use yii\web\Response;
use yii\web\UploadedFile;


class SubmitController extends CommonController
{
    public $layout='submit';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if(!$this->uId){
            return $this->redirect('login.html');
        }
    }

    public function beforeAction($action) {
        $currentaction = $action->id;
        if(in_array($currentaction,['ckeditor-img'])) {
            $action->controller->enableCsrfValidation = false;
        }
        parent::beforeAction($action);
        return true;

}


    /**
     * .web 发布页
     * @return string
     */
    public function actionWeb()
    {
        $model = new WebSource();
        $agreement = Yii::$app->params['web-agreement'];
        if(Yii::$app->request->isPost) {
            $model->scenario = 'submit-web';
            $model->resources= UploadedFile::getInstanceByName('resources');
            $model->uId=$this->uId;
            $model->load(Yii::$app->request->post(), '');
            $checkRes = $model->validate();
            if (!$checkRes) {
                return $this->render('web', [
                    'error' => reset($model->getErrors())[0],
                    'model' => $model,
                    'agreement'=>$agreement
                ]);
            }

            if(!$model->upload()){
                return $this->render('web', [
                    'error' =>'文件上传失败',
                    'model' => $model,
                    'agreement'=>$agreement
                ]);
            }

            $result = $model->addWebSource();
            if(!$result){
                return $this->render('web', [
                    'error' =>'发布失败',
                    'model' => $model,
                    'agreement'=>$agreement
                ]);
            }
            return $this->redirect('submitweb.html');
        }

        return $this->render('web', [
            'model' => $model,
            'agreement'=>$agreement
        ]);
    }


}
