<?php

namespace frontend\models;

use common\models\LogEverDayData;
use Yii;
use yii\base\Model;
/**
 * This is the model class for table "ld_user".
 *
 * @property integer $id
 * @property integer $registerNum
 * @property integer $loginNum
 * @property integer $index_pv
 * @property integer $index_ip
 * @property integer $date
 */


class EveryDayData extends Model
{
    public $id;
    public $registerNum;
    public $loginNum;
    public $index_pv;
    public $index_ip;
    public $submitWebNum;
    public $newWebNum;
    public $date;
    public $redisKey;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->redisKey  ='everyDateData'.date('ymd');
    }


    /*
   * 增加用户注册统计记录
   *
   * */
    public function addRegisterLog(){
        $day =self::_checkDateIsExist(date('Y-m-d',time()));
        if(!$day){
            $log = new LogEverDayData();
            $log->date =date('Y-m-d',time());
            $log->registerNum=1;
            return $log->save();
        }else {
            return $day::updateAllCounters(['registerNum' => 1]);
        }
//        $redis = \Yii::$app->redis;
//        $redis->hincrby(  $this->redisKey ,'registerNum',1);
//        $redis->hincrby(  $this->redisKey ,'loginNum',1);
//        $redis->expire(  $this->redisKey ,36*60*60);
    }

    /*
     * 增加用户登录统计记录
     *
     * */
    public function addLoginLog(){
        $day =self::_checkDateIsExist(date('Y-m-d',time()));
        if(!$day){
                $log = new LogEverDayData();
                $log->date =date('Y-m-d',time());
                $log->loginNum=1;
                return $log->save();

        }else{
            return $day::updateAllCounters( ['loginNum' =>1]);
        }
//        $redis = \Yii::$app->redis;
//        $redis->hincrby(  $this->redisKey ,'loginNum',1);
//        $redis->expire(  $this->redisKey ,36*60*60);
    }

    /*
     * 增加发布网站模板的数量
     *
     * */
    public function addSubmitWebNum(){
        $day =self::_checkDateIsExist(date('Y-m-d',time()));
        if(!$day){
            $log = new LogEverDayData();
            $log->date =date('Y-m-d',time());
            $log->submitWebNum=1;
            return $log->save();

        }else{
            return $day::updateAllCounters( ['submitWebNum' =>1]);
        }

//        $redis = \Yii::$app->redis;
//        $redis->hincrby(  $this->redisKey ,'submitWebNum',1);
//        $redis->expire(  $this->redisKey ,36*60*60);
    }

    /*
     * 增加新上线网站模板的数量
     *
     * */
    public function addNewWebNum(){
        $day =self::_checkDateIsExist(date('Y-m-d',time()));
        if(!$day){
            $log = new LogEverDayData();
            $log->date =date('Y-m-d',time());
            $log->newWebNum=1;
            return $log->save();

        }else{
            return $day::updateAllCounters( ['newWebNum' =>1]);
        }
//        $redis = \Yii::$app->redis;
//        $redis->hincrby(  $this->redisKey ,'newWebNum',1);
//        $redis->expire(  $this->redisKey ,36*60*60);
    }

    /*
     * 检测指定日期的数据是否存在
     *
     * */
    static public function _checkDateIsExist($date){
        return LogEverDayData::findOne(['date'=>date('Y-m-d',time())]);
    }


}
